SELECT * FROM PREFEITO;
SELECT * FROM CIDADE;

SELECT * FROM CIDADE c 
INNER JOIN PREFEITO p ON c.id = p.cidade_id;

SELECT * FROM CIDADE c
LEFT JOIN PREFEITO p ON c.id = p.cidade_id;

SELECT * FROM CIDADE c
RIGHT JOIN PREFEITO p ON c.id = p.cidade_id;